#!/usr/bin/env node
// Embeds skills/flare-forge/SKILL.md into apps/cli/src/forge-skill.gen.ts
// so `forge init --skill` works from the npm bundle (which ships no repo
// files). `forge-init.test.ts` fails when the two drift; re-run this.
//
// Usage: node apps/cli/scripts/gen-skill.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, "..", "..", "..");
const skill = readFileSync(join(repo, "skills", "flare-forge", "SKILL.md"), "utf8");
const out = join(here, "..", "src", "forge-skill.gen.ts");
writeFileSync(
  out,
  [
    "// Generated by apps/cli/scripts/gen-skill.mjs from skills/flare-forge/SKILL.md. Do not edit.",
    `export const FORGE_SKILL_MD: string = ${JSON.stringify(skill)};`,
    "",
  ].join("\n"),
);
console.log(`wrote ${out}`);
