#!/usr/bin/env node
// Embeds skills/flare-*/SKILL.md into apps/cli/src/forge-skill.gen.ts so
// `forge init --skill` and `forge init --global` work from the npm bundle
// (which ships no repo files). `forge-init.test.ts` fails when they
// drift; re-run this.
//
// Usage: node apps/cli/scripts/gen-skill.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, "..", "..", "..");
export const SKILL_NAMES = ["flare-forge", "flare-verify", "flare-setup", "flare-migrate"];
const skills = Object.fromEntries(SKILL_NAMES.map((n) => [n, readFileSync(join(repo, "skills", n, "SKILL.md"), "utf8")]));
const out = join(here, "..", "src", "forge-skill.gen.ts");
writeFileSync(
  out,
  [
    "// Generated by apps/cli/scripts/gen-skill.mjs from skills/flare-*/SKILL.md. Do not edit.",
    `export const FLARE_SKILLS: Record<string, string> = ${JSON.stringify(skills, null, 2)};`,
    `export const FORGE_SKILL_MD: string = FLARE_SKILLS["flare-forge"];`,
    "",
  ].join("\n"),
);
console.log(`wrote ${out}`);
