// Stack detection for one-click adoption: `cli init` and `cli connect`
// scan the repo's manifest files, name the stack, and generate a starter
// flare.yml that matches it. Pure filesystem reads — no network, safe to
// run anywhere, deterministic for a given directory listing.

import { existsSync, readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";

export type StackId =
  | "node"
  | "python"
  | "go"
  | "rust"
  | "ruby"
  | "java"
  | "php"
  | "dotnet"
  | "elixir"
  | "generic";

export const KNOWN_STACKS: StackId[] = [
  "node",
  "python",
  "go",
  "rust",
  "ruby",
  "java",
  "php",
  "dotnet",
  "elixir",
  "generic",
];

export function isStackId(value: string): value is StackId {
  return (KNOWN_STACKS as string[]).includes(value);
}

export interface DetectedStack {
  stack: StackId;
  /** Manifest paths (repo-root-relative) that evidenced this stack. */
  evidence: string[];
}

export interface StarterResult {
  stack: StackId;
  yaml: string;
  /** Human notes about choices baked into the starter (lockfile, scripts). */
  notes: string[];
}

function has(cwd: string, name: string): boolean {
  try {
    return existsSync(join(cwd, name));
  } catch {
    return false;
  }
}

function readJson(cwd: string, name: string): Record<string, unknown> | null {
  try {
    const parsed: unknown = JSON.parse(readFileSync(join(cwd, name), "utf8"));
    return typeof parsed === "object" && parsed !== null && !Array.isArray(parsed)
      ? (parsed as Record<string, unknown>)
      : null;
  } catch {
    return null;
  }
}

function topLevelEntries(cwd: string): string[] {
  try {
    return readdirSync(cwd);
  } catch {
    return [];
  }
}

/** Manifest scan in fixed priority order; every match is returned so
 *  polyglot repos (node + python) see all their stacks. The first entry
 *  is the primary stack used for starter generation. */
export function detectStacks(cwd: string): DetectedStack[] {
  const found: DetectedStack[] = [];
  const nodeEvidence = ["package.json", "package-lock.json", "yarn.lock", "pnpm-lock.yaml", "pnpm-workspace.yaml", "bun.lock", "bun.lockb"]
    .filter((f) => has(cwd, f));
  if (nodeEvidence.length > 0) found.push({ stack: "node", evidence: nodeEvidence });
  const pyEvidence = ["pyproject.toml", "requirements.txt", "requirements-dev.txt", "setup.py", "setup.cfg", "Pipfile", "poetry.lock", "uv.lock"]
    .filter((f) => has(cwd, f));
  if (pyEvidence.length > 0) found.push({ stack: "python", evidence: pyEvidence });
  if (has(cwd, "go.mod")) {
    const evidence = ["go.mod", "go.sum", "go.work"].filter((f) => has(cwd, f));
    found.push({ stack: "go", evidence });
  }
  if (has(cwd, "Cargo.toml")) {
    const evidence = ["Cargo.toml", "Cargo.lock"].filter((f) => has(cwd, f));
    found.push({ stack: "rust", evidence });
  }
  if (has(cwd, "Gemfile")) {
    const evidence = ["Gemfile", "Gemfile.lock", "Rakefile"].filter((f) => has(cwd, f));
    found.push({ stack: "ruby", evidence });
  }
  const javaEvidence = ["pom.xml", "build.gradle", "build.gradle.kts", "settings.gradle", "settings.gradle.kts", "gradlew"]
    .filter((f) => has(cwd, f));
  if (javaEvidence.length > 0) found.push({ stack: "java", evidence: javaEvidence });
  if (has(cwd, "composer.json")) {
    const evidence = ["composer.json", "composer.lock"].filter((f) => has(cwd, f));
    found.push({ stack: "php", evidence });
  }
  const dotnetEvidence = topLevelEntries(cwd)
    .filter((f) => /\.(csproj|fsproj|vbproj|sln|slnx)$/i.test(f))
    .sort();
  if (dotnetEvidence.length > 0) found.push({ stack: "dotnet", evidence: dotnetEvidence });
  if (has(cwd, "mix.exs")) found.push({ stack: "elixir", evidence: ["mix.exs"] });
  return found;
}

export function primaryStack(stacks: DetectedStack[]): DetectedStack | null {
  return stacks[0] ?? null;
}

function header(stack: StackId, evidence: string[]): string {
  const via = evidence.length > 0 ? ` (detected from ${evidence.join(", ")})` : "";
  return `# flare.yml — ${stack} starter generated by \`flare init\`${via}.\n# Docs: docs/PIPELINES.md — edit freely, re-running init never overwrites this file.\n`;
}

function job(name: string, steps: string[], extra?: string): string {
  const lines = [`jobs:`, `  ${name}:`];
  if (extra) lines.push(extra);
  lines.push(`    steps:`);
  for (const step of steps) lines.push(`      - run: ${step}`);
  return `${lines.join("\n")}\n`;
}

function nodePackageManager(cwd: string): { install: string; test: string; evidence: string } {
  if (has(cwd, "yarn.lock")) return { install: "yarn install --frozen-lockfile", test: "yarn test", evidence: "yarn.lock" };
  if (has(cwd, "pnpm-lock.yaml")) return { install: "pnpm install --frozen-lockfile", test: "pnpm test", evidence: "pnpm-lock.yaml" };
  if (has(cwd, "bun.lockb") || has(cwd, "bun.lock")) return { install: "bun install --frozen-lockfile", test: "bun test", evidence: "bun.lock" };
  return { install: "npm ci", test: "npm test", evidence: "package.json" };
}

function nodeScripts(cwd: string): Record<string, string> {
  const pkg = readJson(cwd, "package.json");
  const scripts = pkg?.["scripts"];
  if (typeof scripts !== "object" || scripts === null || Array.isArray(scripts)) return {};
  const out: Record<string, string> = {};
  for (const [k, v] of Object.entries(scripts as Record<string, unknown>)) {
    if (typeof v === "string") out[k] = v;
  }
  return out;
}

/** Build a starter flare.yml for one stack. Every starter is a valid
 *  pipeline (single `verify` job); choices prefer the repo's own
 *  manifests (lockfiles, scripts) over guesses. */
export function generateStarter(cwd: string, stack: StackId): StarterResult {
  const notes: string[] = [];
  switch (stack) {
    case "node": {
      const pm = nodePackageManager(cwd);
      const scripts = nodeScripts(cwd);
      notes.push(`package manager from ${pm.evidence}`);
      const steps = [pm.install];
      if (scripts["build"]) steps.push(pm.test.replace(/ test$/, " run build"));
      steps.push(pm.test);
      const cache = `    cache:\n      key: node-modules\n      paths: [node_modules]`;
      return { stack, notes, yaml: `${header(stack, [pm.evidence])}${job("verify", steps, cache)}` };
    }
    case "python": {
      const steps: string[] = [];
      if (has(cwd, "requirements.txt")) {
        steps.push("pip install -r requirements.txt");
        notes.push("install from requirements.txt");
      } else if (has(cwd, "pyproject.toml")) {
        steps.push("pip install -e .");
        notes.push("install from pyproject.toml");
      } else {
        steps.push("pip install pytest");
        notes.push("no requirements file — installing pytest only");
      }
      steps.push("python -m pytest");
      return { stack, notes, yaml: `${header(stack, detectStacks(cwd).find((s) => s.stack === "python")?.evidence ?? [])}${job("verify", steps)}` };
    }
    case "go": {
      return { stack, notes, yaml: `${header(stack, ["go.mod"])}${job("verify", ["go build ./...", "go test ./..."])}` };
    }
    case "rust": {
      return { stack, notes, yaml: `${header(stack, ["Cargo.toml"])}${job("verify", ["cargo build", "cargo test"])}` };
    }
    case "ruby": {
      const specDir = has(cwd, "spec");
      const testCmd = specDir ? "bundle exec rspec" : "bundle exec rake";
      notes.push(specDir ? "spec/ found — running rspec" : "no spec/ — running the default rake task");
      return { stack, notes, yaml: `${header(stack, ["Gemfile"])}${job("verify", ["bundle install", testCmd])}` };
    }
    case "java": {
      if (has(cwd, "pom.xml")) {
        notes.push("maven build (pom.xml)");
        return { stack, notes, yaml: `${header(stack, ["pom.xml"])}${job("verify", ["mvn -q test"])}` };
      }
      const wrapper = has(cwd, "gradlew") ? "./gradlew" : "gradle";
      notes.push(`gradle build (${wrapper} test)`);
      return { stack, notes, yaml: `${header(stack, ["build.gradle"])}${job("verify", [`${wrapper} test`])}` };
    }
    case "php": {
      const composer = readJson(cwd, "composer.json");
      const scripts = composer?.["scripts"];
      const hasTest = typeof scripts === "object" && scripts !== null && !Array.isArray(scripts) && typeof (scripts as Record<string, unknown>)["test"] === "string";
      const testCmd = hasTest ? "composer test" : "vendor/bin/phpunit";
      notes.push(hasTest ? "composer test script found" : "no composer test script — running phpunit directly");
      return { stack, notes, yaml: `${header(stack, ["composer.json"])}${job("verify", ["composer install", testCmd])}` };
    }
    case "dotnet": {
      return { stack, notes, yaml: `${header(stack, detectStacks(cwd).find((s) => s.stack === "dotnet")?.evidence ?? [])}${job("verify", ["dotnet build", "dotnet test"])}` };
    }
    case "elixir": {
      return { stack, notes, yaml: `${header(stack, ["mix.exs"])}${job("verify", ["mix deps.get", "mix test"])}` };
    }
    case "generic": {
      notes.push("no manifests found — edit the placeholder steps");
      return {
        stack,
        notes,
        yaml: `${header(stack, [])}jobs:\n  verify:\n    steps:\n      - run: ./run-tests.sh # TODO: replace with your build/test commands\n`,
      };
    }
  }
}

/** One-line human summary used by `init`/`connect` output. */
export function formatStacks(stacks: DetectedStack[]): string {
  if (stacks.length === 0) return "none detected";
  return stacks.map((s) => `${s.stack} (${s.evidence.join(", ")})`).join(" + ");
}
